import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "./_components/Header";
import { Footer } from "./_components/Footer";
import { SideBar } from "./_components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "お手軽ブログ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header />
        <main className="font-body flex min-h-screen flex-row">
          <SideBar />
          <div className="bg-cyan-100 w-11/12">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
