import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { SideBar } from "./components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "なかにしの技術ブログ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header />
        <main className="font-body flex h-screen min-h-screen flex-row items-center">
          <SideBar />
          <div className="bg-neutral-200 w-11/12">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
